### ISSUE TITLE
getStreamAsBuffer() does not work anymore for larger file sizes (e.g. PDFKit)

### ISSUE THREAD

**Issue by malte94** [sindresorhus/get-stream#55] opened 2023-06-30 18:42 UTC
Hey there,

The "getStreamAsBuffer()" will not work anymore for larger file sizes. 

Here's an exemplary PDF output which includes many elements with a larger text. As soon as the Blob file size exceeds approx. 15743 bytes, nothing is either sent to the frontend or catched as an error.

The doc.end() is always outputted correctly. 

When I slice the to a certain amount, the PDF is sent to the frontend correctly.

Thank you!

```
  // Create a table for each entry in logbook.entries

  doc.fontSize(10);
  doc.text("", doc.x, doc.y + 10);

  logbook.entries
      .filter(element => new Date(element.date).getFullYear() == year)
      .slice(0, 200)
      .forEach(element => {
          doc.text(element.text);
      });

  // Finalize

  doc.end();

  console.log(doc)

  return await getStreamAsBuffer(doc);
```

**Comment by sindresorhus** [comment] 2023-07-01 18:59
Duplicate of #52

**Closed by sindresorhus** 2023-07-01 18:59 UTC
